version: '3.8'

services:
  postgres:
    extends:
      file: ./services/postgres/service.yml
      service: postgres

  prometheus:
    extends:
      file: ./services/prometheus/service.yml
      service: prometheus

  grafana:
    extends:
      file: ./services/grafana/service.yml
      service: grafana

  keycloak:
    extends:
      file: ./services/keycloak/service.yml
      service: keycloak

  postgres-exporter:
    extends:
      file: ./services/postgres-exporter/service.yml
      service: postgres-exporter

networks:
  devops-net:
    driver: bridge
    name: devops-net

volumes:
  postgres_data:
  prometheus_data:
  grafana_data: