version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD:-postgres123}
      POSTGRES_DB: ${POSTGRES_ROOT_DB:-postgres}
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./configs/postgres/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "54322:5432"
    networks:
      - devops-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_ROOT_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped