global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'keycloak'
    metrics_path: '/metrics'  # Novo endpoint padrão
    static_configs:
      - targets: ['keycloak:8080']
    scheme: http
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']