{
 "title": "01 - PostgreSQL Monitoring - Multi-Database",
 "tags": [
  "postgres",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Instance", "label": "Instance", "query": "label_values(pg_up, instance)" },
   { "name": "Interval", "label": "Interval", "query": "30s,1m,5m,15m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "Global Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PostgreSQL Version",
   "type": "singlestat",
   "description": "Source: server_version_num",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pg_settings_server_version_num)"
    }
   ]
  },
  {
   "title": "Active clients",
   "type": "singlestat",
   "description": "Clients executing Statements.\n\nSource: pg_stat_activity",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\",instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "Connections used",
   "type": "gauge",
   "description": "Percentage of max_connections used",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends)/max(pg_settings_max_connections)"
    }
   ]
  },
  {
   "title": "Shared Buffer Hits",
   "type": "gauge",
   "description": "Shared buffer hits vs reads from disc",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{instance=~\"$Instance\"})/(sum(pg_stat_database_blks_hit{instance=~\"$Instance\"})+sum(pg_stat_database_blks_read{instance=~\"$Instance\"}))*100"
    }
   ]
  },
  {
   "title": "Commit Ratio",
   "type": "gauge",
   "description": "Transaction committed vs rollbacked",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_xact_commit{instance=\"$Instance\"})/(sum(pg_stat_database_xact_commit{instance=\"$Instance\"}) + sum(pg_stat_database_xact_rollback{instance=\"$Instance\"}))"
    }
   ]
  },
  {
   "title": "PostgreSQL Uptime",
   "type": "singlestat",
   "description": "Source: pg_postmaster_start_time()",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time()-(pg_postmaster_start_time_seconds{instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "singlestat",
   "description": "Transactions committed + roolback per minute\n\nSource: pg_stat_database,xact_commit + xact_rollback",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_xact_commit{instance=\"$Instance\"}[$Interval])))+sum((rate(pg_stat_database_xact_rollback{instance=\"$Instance\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Query rate",
   "type": "singlestat",
   "description": "Statements executed per Minute.\n\nSource: pg_stat_statements.calls",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((rate(pg_stat_statements_calls{instance=\"$Instance\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Total database size",
   "type": "singlestat",
   "description": "Size of all databases in $Instance.\n\nSource: pg_database_size()",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pg_database_size{instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "Average query runtime",
   "type": "singlestat",
   "description": "Source: pg_stat_statements.total_time / pg_stat_statements.calls",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((delta(pg_stat_statements_total_time_seconds{instance=\"$Instance\"}[$Interval])))/sum((delta(pg_stat_statements_calls{instance=\"$Instance\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "singlestat",
   "description": "Setting: shared_buffers in PostgreSQL.conf",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "singlestat",
   "description": "Setting: max_connections in postgreSQL.conf",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_max_connections{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Connections by state (stacked)",
   "type": "graph",
   "description": "View: pg_stat_activity",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{instance=\"$Instance\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Connections by database (stacked)",
   "type": "graph",
   "description": "View: pg_stat_activity",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_activity_count{instance=\"$Instance\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "description": "1 Minute rate of transactions committed or rollback.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum ((rate(pg_stat_database_xact_commit[$Interval])))",
     "legendFormat": "committed"
    },
    {
     "expr": "sum ((rate(pg_stat_database_xact_rollback[$Interval])))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Tuples inserts/updates/deletes",
   "type": "graph",
   "description": "Source: pg_stat_database",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_tup_inserted{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_updated{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_deleted{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "I/O Read/Write time",
   "type": "graph",
   "description": "* blk_read_time: Time spent reading data file blocks by backends in this database, in milliseconds\n* blk_write_time: Time spent writing data file blocks by backends in this database, in milliseconds\n\ntrack_io_timings needs to be activated",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum ((rate(pg_stat_database_blk_read_time{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "blk_read_time"
    },
    {
     "expr": "sum ((rate(pg_stat_database_blk_write_time{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "blk_write_time"
    }
   ]
  },
  {
   "title": "Tuples fetched/returned",
   "type": "graph",
   "description": "Source: pg_stat_database\n\n* tup_fetched: rows needed to satisfy queries\n* tup_returned: rows read/scanned",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_tup_fetched{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_returned{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "Locks by state",
   "type": "graph",
   "description": "Source: pg_locks",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{instance=\"$Instance\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Deadlocks by database",
   "type": "graph",
   "description": "Should be 0 \n\nSource: pg_stat_database\n\nWith log_lock_waits turned on, deadlocks will be logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_database_deadlocks{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temporary files by database",
   "type": "graph",
   "description": "Should be 0. If temporary files are created, it can indicate insufficient work_mem. With log_temp_files the creation of temporary files are logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_database_temp_files{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "Database Specific Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Database Size Comparison",
   "type": "graph",
   "description": "Database size over time for Keycloak and Jenkins databases",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_database_size{datname=\"devops_keycloak\"}",
     "legendFormat": "Keycloak DB Size"
    },
    {
     "expr": "pg_database_size{datname=\"db_jenkins\"}",
     "legendFormat": "Jenkins DB Size"
    }
   ]
  },
  {
   "title": "Database Connections Comparison",
   "type": "graph",
   "description": "Connection count for Keycloak and Jenkins databases",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"devops_keycloak\"}",
     "legendFormat": "Keycloak Connections"
    },
    {
     "expr": "pg_stat_database_numbackends{datname=\"db_jenkins\"}",
     "legendFormat": "Jenkins Connections"
    }
   ]
  },
  {
   "title": "Transaction Rate Comparison",
   "type": "graph",
   "description": "Transaction rate comparison between Keycloak and Jenkins databases",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"devops_keycloak\"}[$Interval]) + rate(pg_stat_database_xact_rollback{datname=\"devops_keycloak\"}[$Interval])",
     "legendFormat": "Keycloak Transactions"
    },
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"db_jenkins\"}[$Interval]) + rate(pg_stat_database_xact_rollback{datname=\"db_jenkins\"}[$Interval])",
     "legendFormat": "Jenkins Transactions"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio Comparison",
   "type": "graph",
   "description": "Cache hit ratio comparison between Keycloak and Jenkins databases",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{datname=\"devops_keycloak\"}/(pg_stat_database_blks_hit{datname=\"devops_keycloak\"}+pg_stat_database_blks_read{datname=\"devops_keycloak\"})*100",
     "legendFormat": "Keycloak Cache Hit %"
    },
    {
     "expr": "pg_stat_database_blks_hit{datname=\"db_jenkins\"}/(pg_stat_database_blks_hit{datname=\"db_jenkins\"}+pg_stat_database_blks_read{datname=\"db_jenkins\"})*100",
     "legendFormat": "Jenkins Cache Hit %"
    }
   ]
  }
 ]
}